"""One ReelForge scene, generated by the proven Wan2GP command.

The polling notebook pastes this module and calls ``run_kaggle_session``.
Tests import it directly. Nothing here downloads weights, starts Kaggle, or
imports the Diffusers worker.

Proven settings, from the run that produced an 81-frame H.264 file:

    CUDA_VISIBLE_DEVICES=0 python wgp.py --process <settings.json> \\
        --output-dir <out> --gpu cuda:0 --attention sdpa --profile 5 \\
        --fp16 --verbose 2

Model ``t2v_1.3B``, 416x240, 81 frames, 20 steps, seed 1, profile 5.
81 / 16 = 5.0625 seconds. A scene of any other length is failed before
``wgp.py`` starts, and a failed run does not rewrite those settings.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Callable, Mapping

COMMIT = "b8b18f8114e432eea8f3d7e853a51dd91fa99571"
MODEL_TYPE = "t2v_1.3B"
RESOLUTION = "416x240"
WIDTH = 416
HEIGHT = 240
FRAMES = 81
FPS = 16
STEPS = 20
SEED = 1
ATTENTION = "sdpa"
PROFILE = "5"
GPU = "cuda:0"
SCENE_SECONDS = 5
PROVEN_SECONDS = FRAMES / FPS
PROVIDER = "wan"
WORKER_ID = "wan2gp-1"

Generate = Callable[[Path, Path, Path, Path], int]
Probe = Callable[[Path], dict]


def proven_overrides(prompt: str) -> dict:
    """Settings keys the verified notebook wrote over the factory template.

    Width, height, fps, and quality from the job are ignored. The backend
    asks for the export frame (often 1080x1920 at 30 fps) and normalises
    the upload itself.
    """
    return {
        "model_type": MODEL_TYPE,
        "prompt": prompt,
        "resolution": RESOLUTION,
        "video_length": FRAMES,
        "num_inference_steps": STEPS,
        "seed": SEED,
        "repeat_generation": 1,
        "prompt_enhancer": "",
        "spatial_upsampling": "",
        "temporal_upsampling": "",
        "override_profile": int(PROFILE),
        "override_attention": ATTENTION,
        "image_mode": 0,
    }


def generation_argv(python: str, settings_path: str, output_dir: str) -> list[str]:
    return [
        python, "wgp.py",
        "--process", settings_path,
        "--output-dir", output_dir,
        "--gpu", GPU,
        "--attention", ATTENTION,
        "--profile", PROFILE,
        "--fp16",
        "--verbose", "2",
    ]


def generation_env(base: Mapping[str, str], ckpts: Path) -> dict[str, str]:
    env = dict(base)
    env["CUDA_VISIBLE_DEVICES"] = "0"
    env["TOKENIZERS_PARALLELISM"] = "false"
    env["HF_HOME"] = str(ckpts)
    env["HF_HUB_CACHE"] = str(ckpts)
    env["HUGGINGFACE_HUB_CACHE"] = str(ckpts)
    return env


def _whole_seconds(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return None


def decide(job: Mapping[str, Any]) -> dict:
    """Return a generate decision or a non-retryable failure.

    Does not read width, height, fps, quality, or reference_url, and does
    not offer an alternate frame count.
    """
    seconds = _whole_seconds(job.get("seconds"))
    prompt = job.get("prompt")
    if seconds is None:
        reason = "scene duration must be a whole number of seconds"
    elif seconds != SCENE_SECONDS:
        reason = (
            f"scene is {seconds}s; this worker only generates the proven "
            f"{FRAMES}-frame clip ({PROVEN_SECONDS:.4f}s) for a "
            f"{SCENE_SECONDS}-second scene and will not change settings"
        )
    elif not isinstance(prompt, str) or not prompt.strip():
        reason = "the job has no prompt"
    else:
        return {
            "action": "generate",
            "reason": None,
            "retryable": False,
            "settings": proven_overrides(prompt),
        }
    return {"action": "fail", "reason": reason, "retryable": False, "settings": None}


def apply_proven(settings: dict, prompt: str) -> dict:
    """Overwrite only the proven keys. Leave the rest of the template alone."""
    settings.update(proven_overrides(prompt))
    return settings


def validate_probe(info: Mapping[str, Any]) -> str | None:
    codec = info.get("codec")
    width = info.get("width")
    height = info.get("height")
    frames = str(info.get("frames"))
    rate = info.get("rate")
    try:
        duration = float(info.get("duration"))
    except (TypeError, ValueError):
        duration = 0.0
    if codec != "h264" or width != WIDTH or height != HEIGHT or frames != str(FRAMES) or rate != f"{FPS}/1":
        return f"ffprobe did not match H.264, {WIDTH}x{HEIGHT}, {FRAMES} frames, and {FPS} fps."
    if abs(duration - PROVEN_SECONDS) > 0.02:
        return f"Duration {duration} is not {PROVEN_SECONDS} seconds."
    return None


def probe_media(path: Path) -> dict:
    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_format", "-show_streams", "-of", "json", str(path)],
        check=False, text=True, capture_output=True,
    )
    if probe.returncode != 0:
        raise RuntimeError(probe.stderr.strip() or "ffprobe failed")
    info = json.loads(probe.stdout)
    videos = [stream for stream in info.get("streams", []) if stream.get("codec_type") == "video"]
    if len(videos) != 1:
        raise RuntimeError("ffprobe did not find one video stream")
    video = videos[0]
    duration = float(info.get("format", {}).get("duration") or video.get("duration") or 0)
    return {
        "codec": video.get("codec_name"),
        "width": int(video.get("width") or 0),
        "height": int(video.get("height") or 0),
        "frames": video.get("nb_frames"),
        "rate": video.get("r_frame_rate"),
        "duration": duration,
    }


def multipart_payload(filename: str, data: bytes) -> tuple[bytes, str]:
    boundary = "----reelforge-worker"
    head = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
        f"Content-Type: video/mp4\r\n\r\n"
    ).encode()
    body = head + data + f"\r\n--{boundary}--\r\n".encode()
    return body, f"multipart/form-data; boundary={boundary}"


def failure_payload(detail: str, retryable: bool) -> dict:
    return {"detail": detail[:2000], "retryable": retryable}


class ReelForgeClient:
    """The existing worker API. No new routes."""

    def __init__(self, base: str, token: str, worker_id: str = WORKER_ID):
        if not base:
            raise RuntimeError("REELFORGE_API_BASE is not set")
        if not token:
            raise RuntimeError("REELFORGE_WORKER_TOKEN is not set")
        parsed = urllib.parse.urlparse(base.strip())
        if parsed.scheme != "https" or not parsed.netloc or parsed.path not in ("", "/"):
            raise RuntimeError("REELFORGE_API_BASE must be an https origin with no path")
        self.base = base.strip().rstrip("/")
        self.token = token
        self.worker_id = worker_id

    def _request(self, method: str, path: str, body: dict | None = None, timeout: int = 60):
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(self.base + path, data=data, method=method)
        req.add_header("Authorization", f"Bearer {self.token}")
        if data:
            req.add_header("Content-Type", "application/json")
        with urllib.request.urlopen(req, timeout=timeout) as res:
            raw = res.read()
            return json.loads(raw) if raw else {}

    def next_job(self) -> dict | None:
        query = urllib.parse.urlencode({
            "worker_id": self.worker_id, "provider": PROVIDER,
        })
        body = self._request("GET", f"/api/worker/kaggle/jobs/next?{query}")
        return body.get("job")

    def complete(self, job_id: str, clip: Path) -> dict:
        payload, content_type = multipart_payload(clip.name, clip.read_bytes())
        req = urllib.request.Request(
            f"{self.base}/api/worker/kaggle/jobs/{job_id}/complete",
            data=payload, method="POST",
        )
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("Content-Type", content_type)
        try:
            with urllib.request.urlopen(req, timeout=600) as res:
                return json.loads(res.read() or b"{}")
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")[:500]
            raise RuntimeError(f"upload was rejected ({exc.code}): {detail}") from exc

    def fail(self, job_id: str, detail: str, retryable: bool = False) -> dict:
        return self._request(
            "POST", f"/api/worker/kaggle/jobs/{job_id}/fail",
            failure_payload(detail, retryable),
        )


def default_generate(repo: Path, settings_path: Path, output_dir: Path, log_path: Path) -> int:
    env = generation_env(os.environ, repo / "ckpts")
    cmd = generation_argv(sys.executable, str(settings_path), str(output_dir))
    print("$", "CUDA_VISIBLE_DEVICES=0", " ".join(cmd))
    with log_path.open("w", encoding="utf-8") as log:
        completed = subprocess.run(
            cmd, cwd=repo, env=env, check=False, text=True,
            stdout=log, stderr=subprocess.STDOUT,
        )
    tail = log_path.read_text(encoding="utf-8", errors="replace").splitlines()[-40:]
    print("\n".join(tail))
    print("exit_code", completed.returncode)
    return completed.returncode


def _fail(client: ReelForgeClient, job_id: str, detail: str) -> None:
    try:
        client.fail(job_id, detail, retryable=False)
    except Exception as exc:
        raise SystemExit(f"{detail} (failure report also failed: {exc})") from exc
    raise SystemExit(detail)


def _preserved(root: Path) -> dict[Path, tuple[int, int]]:
    kept = [root / "result.mp4", root / "result_5sec.mp4", root / "result_camera_motion.mp4"]
    return {
        path: (path.stat().st_size, path.stat().st_mtime_ns)
        for path in kept if path.is_file()
    }


def _modified_preserved(stamps: Mapping[Path, tuple[int, int]]) -> str | None:
    for path, stamp in stamps.items():
        if (path.stat().st_size, path.stat().st_mtime_ns) != stamp:
            return f"{path.name} was modified."
    return None


def run_kaggle_session(
    *,
    root: Path | None = None,
    environ: Mapping[str, str] | None = None,
    client: Any | None = None,
    generate: Generate | None = None,
    probe: Probe | None = None,
) -> dict:
    """Claim one wan job, generate once, upload once.

    Stops before ``wgp.py`` when the scene is not 5 seconds, the prompt is
    empty, or the proven settings file is missing. A non-zero exit or a
    probe mismatch is reported with retryable false and does not change
    resolution, frames, steps, seed, attention, or profile.
    """
    root = Path(root or "/kaggle/working")
    preflight = root / "wan2gp_preflight"
    repo = root / "Wan2GP"
    if not (preflight / "load_ready.ok").is_file():
        raise SystemExit("Model-load gate has not passed. Nothing was claimed.")
    output_dir = root / "out"
    already = sorted(output_dir.rglob("*.mp4")) if output_dir.is_dir() else []
    if already or (root / "result_wan2gp.mp4").is_file() or (preflight / "generation.ok").is_file():
        raise SystemExit(
            "This session already has a generation output. Nothing was claimed."
        )

    env = os.environ if environ is None else environ
    base = str(env.get("REELFORGE_API_BASE", "")).strip()
    token = str(env.get("REELFORGE_WORKER_TOKEN", "")).strip()
    if not base or not token:
        raise SystemExit(
            "REELFORGE_API_BASE and REELFORGE_WORKER_TOKEN are required. Nothing was claimed."
        )
    worker_id = str(env.get("REELFORGE_WORKER_ID", WORKER_ID))
    api = client if client is not None else ReelForgeClient(base, token, worker_id)

    job = api.next_job()
    if not job:
        raise SystemExit("No pending wan job. Nothing was generated.")
    job_id = str(job["job_id"])
    decision = decide(job)
    if decision["action"] != "generate":
        _fail(api, job_id, decision["reason"])

    settings_path = root / "t2v_1_3B_settings.json"
    if not settings_path.is_file():
        _fail(api, job_id, "settings file is missing; generation was not started")
    settings = json.loads(settings_path.read_text(encoding="utf-8"))
    prompt = decision["settings"]["prompt"]
    apply_proven(settings, prompt)
    settings_path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")

    output_dir.mkdir(exist_ok=True)
    kept = _preserved(root)
    log_path = root / "wan2gp_generate.log"
    runner = generate if generate is not None else default_generate
    code = runner(repo, settings_path, output_dir, log_path)
    modified = _modified_preserved(kept)
    if modified:
        _fail(api, job_id, modified)
    if code != 0:
        _fail(api, job_id, f"wgp.py exited {code}. Settings were not changed.")

    mp4s = sorted(output_dir.rglob("*.mp4"))
    if len(mp4s) != 1:
        _fail(api, job_id, f"expected one MP4, found {len(mp4s)}. The file was not uploaded.")
    source = mp4s[0]
    if source.stat().st_size <= 0:
        _fail(api, job_id, "the MP4 is empty. The file was not uploaded.")

    reader = probe if probe is not None else probe_media
    try:
        info = reader(source)
        problem = validate_probe(info)
    except Exception as exc:
        _fail(api, job_id, f"ffprobe failed: {exc}. The file was not uploaded.")
    if problem:
        _fail(api, job_id, f"{problem} The file was not uploaded.")

    destination = root / "result_wan2gp.mp4"
    shutil.copy2(source, destination)
    modified = _modified_preserved(kept)
    if modified:
        _fail(api, job_id, modified)
    if destination.stat().st_size <= 0:
        _fail(api, job_id, "result_wan2gp.mp4 is empty. The file was not uploaded.")
    try:
        api.complete(job_id, destination)
    except Exception as exc:
        _fail(api, job_id, f"upload failed: {exc}. result_wan2gp.mp4 was kept.")

    (preflight / "generation.ok").write_text("ok\n", encoding="utf-8")
    (preflight / "ffprobe.ok").write_text(str(destination) + "\n", encoding="utf-8")
    print("result_mp4", destination)
    print("ffprobe_validation=passed")
    return {"job_id": job_id, "output": str(destination), "prompt": prompt}
